### ISSUE TITLE
Implement Abstractive Paper Summarization

### ISSUE THREAD

**Issue by pooja8748** [clubgamma/Summarize-papers#11]
Description: Implement an abstractive summarization model that generates concise and coherent summaries of research papers, effectively capturing key ideas while rephrasing the original content

**Comment by Heramb4270** [comment]
hey @pooja8748 can you please assign this issue to me

**Comment by pooja8748** [comment]
Sure!

**Comment by Heramb4270** [comment]
@pooja8748 will u assign me or should i make a pull request
