### ISSUE TITLE
Improve Documentation for Summarization Pipeline

### ISSUE THREAD

**Issue by pooja8748** [clubgamma/Summarize-papers#4]
Description: Add detailed comments and explanations to the summarization_pipeline.py script to explain each step in the pipeline.

**Comment by Krishnap2k4** [comment]
Hey @pooja8748 Can you please assign this to me, Would love to work on this, Thank You!

**Comment by pooja8748** [comment]
Sure!

**Comment by Krishnap2k4** [comment]
@pooja8748 Thank You, please do assign

**Comment by pooja8748** [comment]
Ok, I will do it.
You can start working on this i will mention you by tomorrow.

**Comment by Krishnap2k4** [comment]
Yea sure,
Can you please tell in which folder will I find  summarization_pipeline.py

**Comment by pooja8748** [comment]
You can add it in notebook folder.

**Comment by Krishnap2k4** [comment]
Okay I will update you.

**Comment by pooja8748** [comment]
Ok, let me know.
